baseURL: 'http://gunmabungei.github.io'
languageCode: 'ja-jp'
title: '群馬高専文芸部'
theme: 'PaperMod'
pygmentsStyle: 'trac'
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
#pygmentsUseClassic: true
#pygmentOptions: "linenos=inline"
hasCJKLanguage: true

##グーグルアナリティクスです。nitgc.bungei@gmail.com
googleAnalytics: 'G-EMJ3B56Q5G'
##G-JB3PP8NJDJ


enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

assets:
  theme_color: 'wheat'
  msapplocation_TileColor: 'wheat'


markup:
  goldmark:
    parser:
      attribute:
        block: true

params:
    # header social icons
    color: 'linen'                           # linen, wheat, gray, light
    twitter: 'NITGC_bungei'       
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Theme PaperMod
    # author: ["Me", "You"] # multiple authors


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    homeInfoParams:
        Title: "このサイトの案内"
        Content: > 
            - ***About***  

            -  Aboutでは文芸部についての解説をしています。
            
            - ***Author*** 
            
            - Authorでは作者ごとにインデックスを作っています。
            
            - ***Tag***
            
            - Tagでは作品の種類ごとにインデックスを作っています。
            
            - Novel：小説
            
            - TT：200字小説
            
            - Poem：日記
    socialIcons:
        - name: twitter
          url: "https://twitter.com/NITGC_bungei"
    editPost:
        URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

        # twitter.com/YOUR_TWITTER_ID

taxonomies:
  tag: 'tag'
  category: 'categories'
  author: 'author'

menu:
  main:
    - name: 'Index'
      url: ''
      weight: 1
    - name: 'About'
      url: 'pages/about/'
      weight: 3
    - name: 'Tag'
      url: 'tag'
      weight: 3
    - name: 'Author'
      url: 'author'
      weight: 3