baseURL = 'http://example.org/'
languageCode = 'en-us'
title = '群馬高専文芸部のサイトへようこそ！'
theme = 'paper'

disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'NITGC_bungei'               # twitter.com/YOUR_TWITTER_ID
  github = 'YOUR_GITHUB_ID'                 # github.com/YOUR_GITHUB_ID

  # home page profile
  avatar = '/mainlogo.jpg'                 # gravatar email or image url
  name = '群馬高専の文芸部です〜'
  bio = 'やっはろー'


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)